# Generated by Django 4.2.5 on 2023-10-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_addtaskmodel_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtaskmodel',
            name='barth_date',
            field=models.DateTimeField(default=None),
        ),
    ]
